import { environment } from '../environments/environment'; //Guide_search/myTrips
export const  apiUrl = {
    home                   :  "http://testing.birdapps.org/launderette-v3/cms/api-web-v3/home/home",
    signUpData             : environment.baseApiUrl+ 'home/home',
    signUp                 : environment.baseApiUrl+ 'login/register',
    login                  : environment.baseApiUrl+ 'login/login',
    getInTouch             : environment.baseApiUrl+ 'contact_us_web/contact_us_email',
    trending               : environment.baseApiUrl+ 'home/trending' ,
    guideList              : environment.baseApiUrl+ 'Guide_web/guideList',
    guideDetails           : environment.baseApiUrl+ 'Guide_web/guideDetails',
    forgotPassword         : environment.baseApiUrl+ 'login/forgot_password',
    myTrips                : environment.baseApiUrl+ 'Guide_search/myTripsWeb',
    tripDetail             : environment.baseApiUrl+ 'Guide_search/myTripDetails',
    pendingTripCancel      : environment.baseApiUrl+ 'Guide_search/pendingTripCancel',
    upcomingTripCncel      : environment.baseApiUrl+ 'booking/upcomingTripCancel',
    tripRating             : environment.baseApiUrl+ 'booking/tripRating',
    profileImage           : environment.baseApiUrl+ 'profile/updateprofileimage',
    profileUpdate          : environment.baseApiUrl+ 'profile/updateprofile',
    changePassword         : environment.baseApiUrl+ 'Login/change_password',
    bookNowGuideDetail     : environment.baseApiUrl+ 'guide_search/requestguide',
    emailVerify            : environment.baseApiUrl+ 'Profile/requestEmailVerification',
    keywordSearch          : environment.baseApiUrl+ 'home/keywordSearch',
    categoryList           : environment.baseApiUrl+ 'Combo_category/category',
    categoryTourList       : environment.baseApiUrl+ 'Combo_category/tour',
    categoryListForSupport : environment.baseApiUrl+ 'support/category',
    supportSubmit          : environment.baseApiUrl+ '/support/support',
    enquiry                : environment.baseApiUrl+ 'support/contact',
    gstDetail              : environment.baseApiUrl+ 'booking/gstPayment',
    applyCoupon            : environment.baseApiUrl+ 'referral/referralCheck',
    seeAllTour             : environment.baseApiUrl+ 'Combo_category/tourByCategory',
    destinations           : environment.baseApiUrl+ 'Guide_search/destination',
    searchLanguage         : environment.baseApiUrl+ 'guide_search/cityLanguage',
    tourByCategoryForGuide : environment.baseApiUrl+ 'Combo_category/tourByCategoryForGuide',
    hireMoreGuide          : environment.baseApiUrl+ 'Guide_search/hireGuideMore',
    soloTripSearch         : environment.baseApiUrl+ 'guide_search/hireGuide',
    getCityDestinationList : environment.baseApiUrl+ 'home/cityDestination',
    config                 : environment.baseApiUrl+ 'home/configWeb',
    inboxSideListing       : environment.baseApiUrl+ 'tourist_chat/inboxWeb',
    notification           : environment.baseApiUrl+ 'notification/userNotification',
    bookingStatus          : environment.baseApiUrl+ 'booking/bookingDetails',
    chatDetail             : environment.baseApiUrl+ 'tourist_chat/inbox_detail',
    msgSend                : environment.baseApiUrl+ 'tourist_chat/send',
    getCreditPoints        : environment.baseApiUrl+ 'login/creditPoints',
    langConfig             : environment.baseApiUrl+ 'home/configWeb'
}